content:
  - name: blog
    label: Blog
    path: src/blog
    filename: '{fields.slug}.md'
    type: collection
    view:
      fields: [title, pubDate, tags]
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: slug
        label: Slug
        type: string
        required: true
        pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$'

      - name: pubDate
        label: Publication Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd

      - name: author
        label: Author
        type: string
        required: true
        default: Becky Schmidt

      - name: description
        label: Description
        type: text
        required: true

      - name: tags
        label: Tags
        type: list
        required: true
        field:
          type: string

      - name: body
        label: Body
        type: rich-text
        required: true


settings:
  hide: true
  content:
    merge: true